---
version: "3"

networks:
    fiibot:
        external: false

services:
    fiibot-logger:
        container_name: "fiibot-logger"
        build:
            context: "./"
            dockerfile: "./Dockerfile.dev"
        volumes:
            - ".:/usr/src/bot"
        env_file:
            - ".env"
        depends_on:
            - "db"
        networks:
            - fiibot
    db:
        image: "postgres:13.3-alpine"
        env_file:
            - ".env"
        networks:
            - fiibot
        volumes:
            - ./postgres:/var/lib/postgresql/data
