version: "3"

networks:
  fiibot-logger:
    external: false

services:
  bot:
    build:
      context: ".."
      dockerfile: "./docker/Dockerfile.dev"
    volumes:
      - "../src:/usr/src/bot/src"
      - "../node_modules:/usr/src/bot/node_modules"
    networks:
      - fiibot-logger
    env_file:
      - "../.env"
    tty: true
  db:
    image: "postgres:17.6-alpine"
    env_file:
      - "../.env"
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - fiibot-logger
    ports:
      - "5432:5432"

